# Generated by Django 2.1.3 on 2018-11-19 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translations',
            old_name='english_text',
            new_name='output_text',
        ),
    ]
